name = "cat"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "cat_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "cat.wasm"
command = "npm run build:release"
